### ISSUE TITLE
the release of video features and small preatrained models

### ISSUE THREAD

**Issue by yellow-binary-tree** [zinengtang/VidLanKD#3]
Hi, I am very interested in your work and plan to reproduce it.
Would you mind releasing the video features extracted by 2D&3D encoder, and small (BERT 6L/512H) teacher & student model? 
Thanks!

**Comment by zinengtang** [comment]
Hi! Thanks for your interest.
Unfortunately, I was looking for ways to publicize the features we use for the model. But it is too large to be released. 
Small portion of data cannot reproduce the results. 
I suggest you can scrap the original videos from youtube or request the original videos, and extract features through this scripts: https://github.com/antoine77340/video_feature_extractor. 

Let me know you need some more help.

For small models, we will update it in 2 days and please check till then.
Thanks!
