### ISSUE TITLE
About GLUE data

### ISSUE THREAD

**Issue by yxgnahz** [zinengtang/VidLanKD#4]
Hi, I'm interested in your work. 
I found one thing that is very confusing in download_glue_data.py. I notice that for downloading QQP the address is https://dl.fbaipublicfiles.com/glue/data/STS-B.zip' while for downloading STS-B the address is 'https://dl.fbaipublicfiles.com/glue/data/QQP-clean.zip'. Does this indicate the GLUE results in your paper are reversed for QQP and STS-B?
Thanks in advance.

**Comment by zinengtang** [comment]
That's a good issue. 
This is probably when I upload the code. I used the GLUE benchmark official dataset repo: https://github.com/nyu-mll/GLUE-baselines/blob/master/download_glue_data.py. Theirs is reversed somehow and they didn't fix it.

Our experiments use huggingface version: https://raw.githubusercontent.com/huggingface/transformers/master/utils/download_glue_data.py
So our results should be correct.

I updated the code and instructions accordingly.

**Comment by yxgnahz** [comment]
Thanks very much for your response! 
I tried "https://raw.githubusercontent.com/huggingface/transformers/master/utils/download_glue_data.py", however, I met an error: "HTTP Error 403: Forbidden". It seems that we do not have the access to it? Therefore, could you share us the glue dataset used in your repo via Google Drive?
Many thanks.

**Comment by zinengtang** [comment]
I tried a new script for downloading and it works for me. I uploaded it in the repo. Could you pls check it?

**Comment by yxgnahz** [comment]
This one works. Thanks very much!
