### ISSUE TITLE
Question about kd1 student head

### ISSUE THREAD

**Issue by ylli0218** [zinengtang/VidLanKD#6]
Hi @zinengtang 
Interesting work. One question about the kd1 student head implementation. In your paper you mentioned that the vector representations are from the last hidden state of language models 
<img width="950" alt="image" src="https://user-images.githubusercontent.com/80176838/185497650-902b7e79-cc5c-47aa-88e8-50df87224ab6.png">

In your code 
https://github.com/zinengtang/VidLanKD/blob/46bae35e1342293ee0d3f5035b497f752ea267c1/vlm/model.py#L172
There is one extra student head. Seems the sequence_output and kd_pred1 have exact same dimensions. Could you explain why this extra head is necessary?

**Comment by zinengtang** [comment]
You can refer to this in Sec.3.3 Architecture, where we discuss this head
We also included ablation results in appendix.B

**Comment by ylli0218** [comment]
@zinengtang Thanks. I missed that detail. 

Another question: could you explain the implementation about NST loss a little bit? 
The transpose and later normalization is a bit counter-intuitive, as it normalize along the sequence length. Is this treating the each token as a "Channel" in image? Have you tried NST loss without this transpose operation? 
https://github.com/zinengtang/VidLanKD/blob/46bae35e1342293ee0d3f5035b497f752ea267c1/vlm/model.py#L174
https://github.com/zinengtang/VidLanKD/blob/46bae35e1342293ee0d3f5035b497f752ea267c1/vteacher/loss.py#L16

Also, should the sequence_output.size(1) in line 175 be sequence_output.size(**0**) instead? 
https://github.com/zinengtang/VidLanKD/blob/46bae35e1342293ee0d3f5035b497f752ea267c1/vlm/model.py#L173-L176

**Comment by ylli0218** [comment]
Hi @zinengtang 

Just to follow up if you have any comments about the question I had above. 

Also, I tried to run the distillation step using the teacher model (teacher_base_hingeloss.bin) and script you provided to train a bert-base model from scratch. Same hyper parameters. I am training with FP32 and the training will take some time to finish. But based on the progress so far, I noticed that the distillation loss does not change much (token loss looks ok). This is a little unexpected to me. Do you also see similar curve during your training? 
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/80176838/187306661-fd771c66-fc55-4aa1-90eb-3d0b8953b073.png">

**Comment by zinengtang** [comment]
For the kd1 loss question I recommend you reading https://arxiv.org/abs/1707.01219 where the kd loss comes from. You can gain some intuition of why it is transposed.
For the kd loss convergence, I think you can check some configurations like loss weight, learning rate schedule if you used any.
