### ISSUE TITLE
CLIP video features

### ISSUE THREAD

**Issue by arshiyaaggarwal** [zinengtang/VidLanKD#7]
Hi,

I read the paper and was really fascinated by the work. I was trying to use your model for my own project. I read that you use CLIP features on images as well. I was wondering how to extract the CLIP features as I just saw ResNet based features on the video_extractor repository. Am I missing something? Any help would be appreciated. Thanks!

**Comment by zinengtang** [comment]
Currently, we did not release CLIP features scripts. 
To extract CLIP features is very simple.
1. Obtain image frames from a videos
2. Extract image-level features by using CLIP on each image frame:

install clip here https://github.com/openai/CLIP
```
import torch
import clip

device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("ViT-B/32", device=device)

# get images_frames from a video
images_frames_preprocessed = [preprocess(img)).unsqueeze(0).to(device) for img in images_frames]
with torch.no_grad():
    image_frames_features = [model.encode_image(img) for img in images_frames_preprocessed]
```
